Extension case sensitivity fix
rogeriotaques/droparea pull request #3
Opened 2017-01-18 00:49 UTC by tkrn

2017-01-18 20:32 UTC, rogeriotaques requested changes

2017-01-18 20:32 UTC, rogeriotaques commented on src/droparea.js
> +                if ( o.accepted.indexOf( file.name.substr( file.name.lastIndexOf('.') ).toLowerCase() ) === -1 )
Hi @tkrn ,

Thank you for your contribution. 👍 

What do you think to lower-case the `o.accepted` as well, when comparing to `name.lastIndexOf('.').toLowerCase()`? By doing that, we can ensure that accepted extensions are aways in lower-case too.

Can you add it to your code?

```
if ( o.accepted.toLowerCase().indexOf( file.name.substr( file.name.lastIndexOf('.') ).toLowerCase() ) === -1 )
```

Cheers,

Roger.

2017-01-18 20:51 UTC, tkrn commented
Will do. Then I'll submit a pull request. Good feedback. Thanks!

On Jan 18, 2017, at 3:32 PM, Rog?rio Taques <notifications@github.com<mailto:notifications@github.com>> wrote:


@rogeriotaques requested changes on this pull request.

________________________________

In src/droparea.js<https://github.com/rogeriotaques/droparea/pull/3#pullrequestreview-17318319>:

> @@ -203,7 +203,7 @@
               // check if dropped file is allowed
               if ( o.accepted !== null && typeof o.accepted != 'boolean' )
               {
-                if ( o.accepted.indexOf( file.name.substr( file.name.lastIndexOf('.') ) ) === -1 )
+                if ( o.accepted.indexOf( file.name.substr( file.name.lastIndexOf('.') ).toLowerCase() ) === -1 )


Hi @tkrn<https://github.com/tkrn> ,

Thank you for your contribution. ?

What do you think to lower-case the o.accepted as well, when comparing to name.lastIndexOf('.').toLowerCase()? By doing that, we can ensure that accepted extensions are aways in lower-case too.

Can you add it to your code?

if ( o.accepted.toLowerCase().indexOf( file.name.substr( file.name.lastIndexOf('.') ).toLowerCase() ) === -1 )


Cheers,

Roger.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/rogeriotaques/droparea/pull/3#pullrequestreview-17318319>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AESMg-eZKH0R9lpOmd8-m349ZERa7PLCks5rTnbkgaJpZM4LmWTA>.

2017-01-24 16:00 UTC, rogeriotaques approved these changes

2017-01-24 16:01 UTC, merged